### ISSUE TITLE
Generic-инстансы

### ISSUE THREAD

**Issue by ghost** [DenDragonB/newsserver#1]
Аналогично https://github.com/DenDragonB/echobot/issues/1

**Comment by DenDragonB** [comment]
Готово

**Comment by ghost** [comment]
А с вот с этими можно так же?
```
src/DataBase/Users.hs:instance A.ToJSON User where
src/DataBase/Tags.hs:instance A.ToJSON Tag where
src/DataBase/Posts.hs:instance A.ToJSON News where
src/DataBase/Drafts.hs:instance A.ToJSON Draft where
src/DataBase/Categories.hs:instance A.ToJSON Category where
src/DataBase/Authors.hs:instance A.ToJSON Author where
app/Main.hs:instance Aeson.FromJSON Config where
```

**Comment by DenDragonB** [comment]
для JSON - там не совпадают имена геттеров с полями JSON, потому Generic не стал делать, а вот для FromRow сделал

**Comment by ghost** [comment]
А почему имена полей должны отличаться в хаскеле и  json'e?

**Comment by DenDragonB** [comment]
Сделал. Нужно поправить конфиг. 
поле "name" в группе [database] нужно переименовать в "dbname"

**Comment by ghost** [comment]
Отлично, остался только Main.Config. Так как в хаскеле поля это ф-ии access'оры, то может быть не оч хочется вносить такие имена, как `log`, `db`, `web` в глобальный скоуп. Есть разные решения чтобы избежать ручного написания кастомных инстансов:
* Задать параметр при генерации дженериков `fieldLabelModifier` из `Aeson.Options` в виде ф-ии отображающей имя в хаскеле на имя в жсоне. Например, имея префикс `_` в имени каждого поля, ф-я `drop 1` убирает его, оставляя в жсоне только имя. Таким образом можно менять кейсинг (camel, snake, etc...), добавлять/убирать префиксы/постфиксы для всех полей сразу в объекте, не перечисляя каждый случай вручную. Так меньше шансов на ошибку/баг
* Использовать линзы: `object ^. #field`
* Использовать haskell record dot syntax (Раньше это был препроцессор/плагин, вроде его вмержили в ghc)

Последние два решения позволяют избежать конфликтов имен, т.е. два типа могут иметь одинаковые поля

**Comment by DenDragonB** [comment]
готово
