### ISSUE TITLE
Использование ByteString

### ISSUE THREAD

**Issue by ghost** [DenDragonB/newsserver#10]
Сейчас очень много бизнес логики оперирует с `ByteString`. Это низкоуровневый тип, к тому же у тебя из-за этого получается куча переводов в `String` и `Text` разбросано по коду. Список query параметров можно сразу перевести в `Text` и работать уже с текстом, что имеет больше смысла

**Comment by DenDragonB** [comment]
Сделал парсер параметров

**Comment by ghost** [comment]
Это не избавляет от работы с байтстрингом. В коде все еще куча мест где используется байтстринг, хотя по смыслу там лежит текст

**Comment by DenDragonB** [comment]
сделал
