### ISSUE TITLE
JSON result

### ISSUE THREAD

**Issue by ghost** [DenDragonB/newsserver#11]
При успешном результате возвращается жсон вида
```json
{"result":"Ok","object":[{"name":"Computer","id":1}]}
```
При этом если случилась ошибка, то возвращается просто текст ошибки. Было бы здорово даже ошибки получать в жсоне, например вида:
```json
{"result":"Failure","error":"Error when accessing the database. Contact your administrator."}
```

Второе, это вездесущий `object` который возвращает список для **всех** эндпоинтов. Почему список? `users.add` возвращает всегда строго одну сущность, не 0 и не 10

**Comment by DenDragonB** [comment]
сделал

**Comment by ghost** [comment]
`drafts.publish` все еще возвращает список:
```json
{"result":"Ok","object":[{"main_photo":"photo.jpg","category":"Computers","content":"NewContent","photos":["photo1.png","photo2.jpg"],"header":"NewPost","author":"admin","id":1,"reg_date":"2021-09-10","tags":["Computer"]}]}
```

**Comment by DenDragonB** [comment]
Исправил
