### ISSUE TITLE
Теги

### ISSUE THREAD

**Issue by ghost** [DenDragonB/newsserver#13]
При добавлении драфта можно подать произвольные теги, в том числе те которые не существуют в базе. По хорошему наличие тегов надо проверять во всех эндах (в т.ч. при редактировании поста/драфта). 

При этом в базе теги это просто массивы, т.е. отсутствуют констрейнты на айдишники. Отношение посты <-> теги это many to many (в противоположность one to many), в нормализованной дб такие отношения обычно реализуются в виде таблицы c двумя колонками: `post_id` и `tag_id`, где на их пару наложен `UNIQUE` constraint.

**Comment by DenDragonB** [comment]
Сделал

**Comment by ghost** [comment]
Таблицам `News` и `Draft` теперь не нужны колонки `Tags`

**Comment by ghost** [comment]
В таблицу `DraftToTags` сейчас можно добавить несколько одинаковых тегов к посту, так как уникальность пары (draftid, tagid) ничем не обеспечивается

**Comment by DenDragonB** [comment]
> В таблицу `DraftToTags` сейчас можно добавить несколько одинаковых тегов к посту, так как уникальность пары (draftid, tagid) ничем не обеспечивается

Там UNIQUE при создании таблицы используется.

**Comment by DenDragonB** [comment]
Все сделал

**Comment by ghost** [comment]
Отлично! но заметил вот такой паттерн:
```
  (Query "SELECT d.Id,d.News,d.Header,d.RegDate,d.Author,d.Category, "
+            <> "array_remove(array_agg(t.tagid),NULL),d.Content,d.MainPhoto,d.Photos "
+            <> "FROM Drafts d "
+            <> "LEFT OUTER JOIN draftstotags t ON t.draftid=d.id "
+            <> "WHERE d.Id = ? "
```
Нули не придется убирать из массива если джоин будет внутренним

**Comment by DenDragonB** [comment]
Если у нас тэги не заданы, то внутренний JOIN не найдет совпадений и выдаст пустую таблицу, поэтому используется внешний, который в случае отсутствия тэгов выдаст в соответствующих полях null

**Comment by delfigamer** [comment]
https://github.com/DenDragonB/newsserver/blob/a7156a83b4ed0a2a084b52e43111f881dd274b4c/src/DataBase/sql/0006.sql#L5-L11

Это не обязательно и даже не всегда используется, но в таких вспомогательных таблицах можно обойтись и без отдельного идентификатора, сама пара уже может служить как первичный ключ:

```sql
CREATE TABLE NewsToTags
    ( NewsId INT
    , TagId INT
	, PRIMARY KEY (NewsId,TagId)
    , FOREIGN KEY (NewsId) REFERENCES News (Id) ON DELETE CASCADE ON UPDATE CASCADE
    , FOREIGN KEY (TagId) REFERENCES Tags (Id) ON DELETE CASCADE ON UPDATE CASCADE);

CREATE INDEX NewsToTags_Rev ON NewsToTags (TagId, NewsId);
```

Напоминаю, что в большинстве случаев, `PRIMARY KEY` - это лишь синоним для `UNIQUE NOT NULL`.
