### ISSUE TITLE
Бизнес-логика смешана с текстами запросов

### ISSUE THREAD

**Issue by delfigamer** [DenDragonB/newsserver#16]
Например:
https://github.com/DenDragonB/newsserver/blob/a7156a83b4ed0a2a084b52e43111f881dd274b4c/src/DataBase/Authors.hs#L30-L64

Я считаю, вместо этого лучше вынести запросы к БД на отдельный слой абстракции:
1. Если мы решим перейти с PosthreSQL на другой движок, или даже начнём поддерживать несколько движков одновременно, нам придётся просмотреть больший объём кода, и в ходе изменений есть шанс случайно задеть и сломать и бизнес-логику. Будет лучше, если код, который зависит от конкретного движка БД, будет изолирован от остальной программы.
2. Назначение некоторых запросов может быть неочевидно из их содержания - если запрос вынести в отдельную функцию, название и сигнатура этой функции послужит дополнительной документацией к коду.

    Кроме того, в текущем виде, возможна такая ситуация - в тексте запроса оказалась ошибка, но при прочтении, программист принимает её за должное поведение для данного юз-кейса. В случае, когда запрос выделен в отдельную функцию - эту ошибку можно будет обнаружить по несоответствию между названием и телом этой функции.
3. В сочетании с dependency inversion, это позволит заменить реальную базу данных на моки, что даст возможность протестировать бизнес-логику в изоляции от остального кода и от внешних сервисов (включая движок БД).

**Comment by DenDragonB** [comment]
Готово
