### ISSUE TITLE
Использовать подстановку при построении sql запросов

### ISSUE THREAD

**Issue by ghost** [DenDragonB/newsserver#2]
Конкатенировать строки для получения sql запросов это очень небезопасно, такая уязвимость называется [sql injection](https://portswigger.net/web-security/sql-injection). В `postgresql-simple` есть специальный движок для безопасного подставления значений.

**Comment by DenDragonB** [comment]
сделал где смог

**Comment by ghost** [comment]
Все комбинаторы из `src/DataBase.hs` используют конкатенацию. Это еще может быть ок при подстановке имен полей (которые задаются константами в коде), но это все еще уязвимость при подстановке значений. Например, 
```
addFieldToQueryGraterBS :: BS.ByteString -> BS.ByteString -> BS.ByteString
addFieldToQueryGraterBS field val = if val == ""
    then ""
    else " AND " <> field <> " > '" <> val <> "'"

```
Что, если в качестве `val` я передам `' OR TRUE OR '' > '`? Это позволит получить доступ ко всем строкам, то есть security issue

**Comment by DenDragonB** [comment]
Сделал

**Comment by ghost** [comment]
Зачем нужен `CAST`?
Зачем нужен `AS`?
```
                    _ <- liftIO $ execDBsafe pool
￼                        (Query "WITH "
￼                            <> "newData AS (SELECT CAST (? AS INT) as userid, CAST (? AS TEXT) as about),"
￼                            <> "oldData AS (SELECT id,userid,about from Authors WHERE id = ?)"
￼                            <> "UPDATE Authors SET "
￼                            <> "UserId = COALESCE ((SELECT userid from newData),(SELECT userid from oldData)),"
￼                            <> "About = COALESCE ((SELECT about from newData),(SELECT about from oldData))"
￼                            <> "WHERE Id = (SELECT id from oldData);")
￼                        (uid,about,aid)
```
Можно ли это упростить до: 
```
            _ <- liftIO $ execDBsafe pool $
                                "UPDATE Authors SET "
￼                            <> "UserId = COALESCE (?,userid),"
￼                            <> "About = COALESCE (?,about)"
￼                            <> "WHERE Id = ?;"
￼                        (uid,about,aid)
```
?

**Comment by DenDragonB** [comment]
> Зачем нужен `CAST`?
> Зачем нужен `AS`?

Это приведение типа. Когда подставляется NULL тип может не совпасть.

**Comment by DenDragonB** [comment]
> Можно ли это упростить до:

Оказывается можно...
Я не знал, что можно так напрямую обращаться к данным изменяемой таблицы.

Сделал.

**Comment by DenDragonB** [comment]
Убрал все CAST
