### ISSUE TITLE
Curl скрипты

### ISSUE THREAD

**Issue by ghost** [DenDragonB/newsserver#7]
Сейчас это просто набор url-ов, для запуска которых нужно писать программу/скрипт или копировать каждую строку для запуска

**Comment by DenDragonB** [comment]
Поправил

**Comment by ghost** [comment]
* Спец символы в url'ах ломают строки (например `&`), url'ы должны быть в одинарных или двойных кавычках
* Отсутствуют shebang'и. Это не критично, но крайне желательно
* У sh файлов отсутствуют разрешения на исполнение (см. `chmod`). Тоже не критично, но крайне желательно

**Comment by DenDragonB** [comment]
Проверь разрешения, пожалуйста

**Comment by ghost** [comment]
Ни один гет запрос не работает:
```
wixe@thinkpad newsserver/CURLs$ ./tags.get.sh 
Wrong query parameter%
wixe@thinkpad newsserver/CURLs$ ./users.get.sh
404 - Not found%
wixe@thinkpad newsserver/CURLs$ ./authors.get.sh 
Wrong query parameter%
wixe@thinkpad newsserver/CURLs$ ./categories.get.sh 
Wrong query parameter%
wixe@thinkpad newsserver/CURLs$ ./drafts.get.sh 
Wrong query parameter%
wixe@thinkpad newsserver/CURLs$ ./posts.get.sh 
```
edit, add и delete запросы даже не пробовал пока

**Comment by DenDragonB** [comment]
Переделал
