### ISSUE TITLE
Использование пустой строки по умолчанию если нет параметра в query

### ISSUE THREAD

**Issue by ghost** [DenDragonB/newsserver#9]
В базу вообще нежелательно добавлять пустые строки, для этого желательно валидировать все приходящие значения. Но даже если ничего не валидировать, и позволять добавлять пустые строки, то самому добавлять их точно не стоит. Например, 
```haskell
parseUser :: [( BS.ByteString , Maybe BS.ByteString )] -> User
parseUser = foldr func emptyUser where
    func (pn,pe) puser = case pn of
        "id"         -> puser {id = fromMaybe 0 (pe >>= BS.fromByteString)}
        "last_name"  -> puser {last_name = BS.toString $ fromMaybe "" pe}
        "first_name" -> puser {first_name = BS.toString $ fromMaybe "" pe}
        "name"       -> puser {name = BS.toString $ fromMaybe "" pe}
        "avatar"     -> puser {avatar = BS.toString $ fromMaybe "" pe}
        "pass"       -> puser {upass = BS.toString $ makeHash $ fromMaybe "" pe}
        "token"      -> puser {token = BS.toString $ fromMaybe "" pe}
        _            -> puser
```
в этом случае мы добавляем пустой токен и пароль, что значит что отправить запрос за этого пользователя можно без авторизации (послав пустой токен/пароль в любом запросе/в момент логина). Пользователь с пустым именем особо смысла не имеет тож. 

В случае с айди тоже самое, почему ставится 0? Правда тут еще один вопрос, а почему мы вообще айди берем из запроса? Айди обычно генерируется, в приложении или в базе и возвращается пользователю

Тут может быть такой контр аргумент, что в базе могут быть какиенибудь констрейнты (типа чтобы пустая строка не была равна нулю), но переносить валидацию на базу это значит размазывать бизнес логику по меж аппом и базой. Это же кстати касается `cast`ов в sql. Переводить строку в тип лучше в аппе, а не в базе

**Comment by DenDragonB** [comment]
Это просто приведение запроса в другую форму данных.

**Comment by DenDragonB** [comment]
Убрал

**Comment by ghost** [comment]
```
    let userName = fromMaybe "" (mUserName :: Maybe T.Text)
    let userPass = fromMaybe "" (mPass :: Maybe T.Text)
```
Вот это прям уязвимость. Получается добавляется пользователь у которого имя и пароль пустые строки. По хорошему надо выкидывать ошибку что эти параметры должны быть а их нет

**Comment by ghost** [comment]
> Это просто приведение запроса в другую форму данных.

Да, но это приведение с потерями. Тип результат функции -- `User`, он не подразумевает возможность ошибки, как, например `Maybe User` или `Either SomeError User`. При этом ошибка вполне может случиться если какого то поля нету или это поле не смогли распарсить. 

Иметь `fromMaybe` имеет смысл только для очень узкого набора полей. Например, offset и limit, если их нет то можно иметь для них значения по умолчанию. А вот иметь значения по умолчанию (равные нулю или пустой строке) это не имеет смысла и чревато уязвимостями. Если что то не можем распарсить или чего то нет -- выкидываем 400 ошибку.

Другой момент, это подстановка Maybe значений в sql запрос. Во многих случаях это ок и даже удобно, например, в search запросе почти все поля опциональные, [троичная логика](https://ru.wikipedia.org/wiki/%D0%A2%D1%80%D0%BE%D0%B8%D1%87%D0%BD%D0%B0%D1%8F_%D0%BB%D0%BE%D0%B3%D0%B8%D0%BA%D0%B0) позволяет игнорировать некоторые серч параметры. Но в случае когда просто не получилось распарсить поле или его нет, и мы отправляем это как Nothing в sql запросе, то там подставляется null в место где **должно** быть какоето значение. И даже если у тебя там в базе на эту колонку висит констрейнт `NOT NULL` и тебе вернется ошибка, она скорее всего вернется как 500 что совсем не ок, ведь это bad request а не internal error

**Comment by ghost** [comment]
Если посмотреть на тип функции `parseParam` (и похожие на нее) то видно логическую несостыковку: она возвращает мейби но при этом внутри выбрасывает ошибку. Если ты разворачиваешь Maybe и на Nothing выкидываешь ошибку, то на Just можно возвращать чистое значение, а не Maybe

**Comment by DenDragonB** [comment]
> ```
>     let userName = fromMaybe "" (mUserName :: Maybe T.Text)
>     let userPass = fromMaybe "" (mPass :: Maybe T.Text)
> ```
> 
> Вот это прям уязвимость. Получается добавляется пользователь у которого имя и пароль пустые строки. По хорошему надо выкидывать ошибку что эти параметры должны быть а их нет

Поправил
